### ISSUE TITLE
first tests for Oscillator

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.sound.js-ARCHIVE#5]
i haven't looked into the testing, i understand it's being done with
https://mochajs.org/
do you have experience with that @blechdom?
can we write some custom testing for the oscillator class?

**Comment by blechdom** [comment]
> i haven't looked into the testing, i understand it's being done with
> https://mochajs.org/
> do you have experience with that @blechdom?
> can we write some custom testing for the oscillator class?
> 
> 
> 

Yes! I will look into it this week and see what can be done!

**Comment by montoyamoraga** [comment]
tests are being worked on another issue
