### ISSUE TITLE
create TO DO list to track progress

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.sound.js-ARCHIVE#64]
so that everybody can see what is done, what needs help!

**Comment by montoyamoraga** [comment]
i tried milestones,
but i settled on projects,
right now they are private,
i couldn't change them to public
because i am not an owner of the processing organization
tagging @Qianqianye for help to make my projects public :)

**Comment by Qianqianye** [comment]
I have updated all [three projects](https://github.com/processing/p5.sound.js/projects?query=is%3Aopen) to public.
