### ISSUE TITLE
minimum viable product: just add a link to the p5.js website of the README of this new library, not the reference

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.sound.js-ARCHIVE#84]

**Comment by AdityyaX** [comment]
hey @montoyamoraga 
I hope this message finds you well.
I'm eager to work on this issue and would greatly appreciate it if you could assign this issue to me. 
If someone is not working in this issue.

**Comment by montoyamoraga** [comment]
hi thanks, sure go for it :)
