### ISSUE TITLE
FEAT: Adding a sidebar.

### ISSUE THREAD

**Issue by Ayush-Vish** [processing/p5.sound.js-ARCHIVE#96]
### Increasing Access

![image](https://github.com/processing/p5.sound.js/assets/127919475/a22fc8b1-cb4c-47de-8a0c-0d54e73dbcf9)

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

We Will make a new sidebar for the mobile view.

**Comment by montoyamoraga** [comment]
hi @Ayush-Vish please file this issue on the p5.js repo thanks!
